theme: jekyll-theme-hacker
title: "Ryan Barrage | Systems & Gameplay Architect"
description: "PhD Researcher & Game Developer specializing in networked systems and computational modelling."
show_downloads: false
google_analytics:
